import { requireUser } from "@/lib/auth/session";
import { formatMinutes, getPendingRoutineItemsForType } from "@/lib/activity-logs/page-data";
import { prisma } from "@/lib/prisma";

import { createLanguage, createLanguageLog, deleteLanguage, updateLanguageLog } from "./actions";

type SearchParams = { error?: string; message?: string };

export default async function LanguagePage({ searchParams }: { searchParams?: SearchParams }) {
  const user = await requireUser();
  const [languages, routineItems, logs] = await Promise.all([
    prisma.userLanguage.findMany({ where: { userId: user.id }, orderBy: { name: "asc" } }),
    getPendingRoutineItemsForType(user.id, "language"),
    prisma.languageLog.findMany({ where: { userId: user.id }, include: { language: true }, orderBy: { createdAt: "desc" } })
  ]);
  const totals = languages.map((language) => {
    const languageLogs = logs.filter((log) => log.language.id === language.id);
    return { id: language.id, name: language.name, durationMinutes: languageLogs.reduce((total, log) => total + log.durationMinutes, 0), logs: languageLogs };
  });

  return <section className="space-y-5"><Header title="Language Details" error={searchParams?.error} message={searchParams?.message} /><Master languages={languages} /><Pending items={routineItems} /><Totals totals={totals} /><History logs={logs} /></section>;
}

function Header({ error, message, title }: { error?: string; message?: string; title: string }) { return <><div><h1 className="text-3xl font-semibold">{title}</h1><p className="mt-2 text-slate-300">Manage languages, fill details for completed routine items, and track accumulated language duration.</p></div>{error ? <p className="rounded-md border border-red-500/40 bg-red-500/10 px-3 py-2 text-sm text-red-200">{error}</p> : null}{message ? <p className="rounded-md border border-emerald-500/40 bg-emerald-500/10 px-3 py-2 text-sm text-emerald-200">{message}</p> : null}</>; }
function Master({ languages }: { languages: { id: string; name: string }[] }) { return <section className="rounded-lg border border-slate-800 bg-slate-900 p-5"><h2 className="text-xl font-semibold">Language List</h2><form action={createLanguage} className="mt-4 grid gap-3 md:grid-cols-[1fr_auto]"><label className="grid gap-1 text-sm">Add Language<input className="rounded-md border border-slate-700 bg-slate-950 px-3 py-2 text-slate-50" name="name" placeholder="English, Mandarin" required /></label><button className="self-end rounded-md bg-primary px-4 py-2 font-medium text-white" type="submit">Add</button></form>{languages.length === 0 ? <p className="mt-3 text-sm text-slate-400">No languages yet.</p> : <ul className="mt-4 space-y-2">{languages.map((language) => <li className="flex items-center justify-between gap-3 rounded-md border border-slate-800 bg-slate-950 px-3 py-2" key={language.id}><span>{language.name}</span><form action={deleteLanguage}><input name="id" type="hidden" value={language.id} /><button className="text-sm text-red-200" type="submit">Delete</button></form></li>)}</ul>}</section>; }
function Pending({ items }: { items: { id: string; displayName: string; durationMinutes: number }[] }) { return <section className="rounded-lg border border-slate-800 bg-slate-900 p-5"><h2 className="text-xl font-semibold">Pending Language Details</h2>{items.length === 0 ? <p className="mt-2 text-sm text-slate-400">No completed language items are waiting for details.</p> : <div className="mt-4 space-y-3">{items.map((item) => <form action={createLanguageLog} className="grid gap-3 rounded-md border border-slate-800 bg-slate-950 p-4" key={item.id}><input name="dailyRoutineItemId" type="hidden" value={item.id} /><h3 className="font-medium">{item.displayName}</h3><Input defaultValue={String(item.durationMinutes)} label="Duration Minutes" name="durationMinutes" type="number" /><Input label="Material" name="material" /><Textarea label="Vocabulary" name="vocabulary" /><Textarea label="Notes" name="notes" /><Button label="Save Language Detail" /></form>)}</div>}</section>; }
function Totals({ totals }: { totals: { id: string; name: string; durationMinutes: number; logs: LanguageLogWithLanguage[] }[] }) { return <section className="rounded-lg border border-slate-800 bg-slate-900 p-5"><h2 className="text-xl font-semibold">Total Duration</h2>{totals.length === 0 ? <p className="mt-2 text-sm text-slate-400">No language duration yet.</p> : <div className="mt-4 space-y-3">{totals.map((item) => <details className="rounded-md border border-slate-800 bg-slate-950 p-3" key={item.id}><summary className="cursor-pointer font-medium">{item.name}: {formatMinutes(item.durationMinutes)}</summary><ul className="mt-3 space-y-2 text-sm text-slate-300">{item.logs.length === 0 ? <li>No history yet.</li> : item.logs.map((log) => <li key={log.id}>{log.logDate.toISOString().slice(0, 10)} - {formatMinutes(log.durationMinutes)}{log.notes ? ` - ${log.notes}` : ""}</li>)}</ul></details>)}</div>}</section>; }
function History({ logs }: { logs: LanguageLogWithLanguage[] }) { return <section className="rounded-lg border border-slate-800 bg-slate-900 p-5"><h2 className="text-xl font-semibold">History</h2>{logs.length === 0 ? <p className="mt-2 text-sm text-slate-400">No logs yet.</p> : <div className="mt-4 space-y-3">{logs.slice(0, 10).map((log) => <form action={updateLanguageLog} className="grid gap-3 rounded-md border border-slate-800 bg-slate-950 p-4" key={log.id}><input name="id" type="hidden" value={log.id} /><h3 className="font-medium">{log.language.name} - {log.logDate.toISOString().slice(0, 10)}</h3><Input defaultValue={String(log.durationMinutes)} label="Duration Minutes" name="durationMinutes" type="number" /><Input defaultValue={log.material ?? ""} label="Material" name="material" /><Textarea defaultValue={log.vocabulary ?? ""} label="Vocabulary" name="vocabulary" /><Textarea defaultValue={log.notes ?? ""} label="Notes" name="notes" /><Button label="Update Language Detail" /></form>)}</div>}</section>; }
function Input({ defaultValue, label, name, type = "text" }: { defaultValue?: string; label: string; name: string; type?: string }) { return <label className="grid gap-1 text-sm">{label}<input className="rounded-md border border-slate-700 bg-slate-950 px-3 py-2 text-slate-50" defaultValue={defaultValue} name={name} required={name === "durationMinutes"} type={type} /></label>; }
function Textarea({ defaultValue, label, name }: { defaultValue?: string; label: string; name: string }) { return <label className="grid gap-1 text-sm">{label}<textarea className="rounded-md border border-slate-700 bg-slate-950 px-3 py-2 text-slate-50" defaultValue={defaultValue} name={name} rows={3} /></label>; }
function Button({ label }: { label: string }) { return <button className="rounded-md bg-primary px-4 py-2 font-medium text-white" type="submit">{label}</button>; }

type LanguageLogWithLanguage = { id: string; logDate: Date; durationMinutes: number; material: string | null; vocabulary: string | null; notes: string | null; language: { id: string; name: string } };
