import { requireUser } from "@/lib/auth/session";
import { formatMinutes, getPendingRoutineItemsForType } from "@/lib/activity-logs/page-data";
import { prisma } from "@/lib/prisma";

import { createExerciseLog, createExerciseType, deleteExerciseType, updateExerciseLog } from "./actions";

type SearchParams = { error?: string; message?: string };

export default async function ExercisePage({ searchParams }: { searchParams?: SearchParams }) {
  const user = await requireUser();
  const [exercises, routineItems, logs] = await Promise.all([
    prisma.exerciseType.findMany({ where: { userId: user.id }, orderBy: { name: "asc" } }),
    getPendingRoutineItemsForType(user.id, "exercise"),
    prisma.exerciseLog.findMany({ where: { userId: user.id }, include: { exerciseType: true }, orderBy: { createdAt: "desc" } })
  ]);
  const totals = exercises.map((exercise) => {
    const exerciseLogs = logs.filter((log) => log.exerciseType.id === exercise.id);
    return { id: exercise.id, name: exercise.name, durationMinutes: exerciseLogs.reduce((total, log) => total + log.durationMinutes, 0), logs: exerciseLogs };
  });

  return <section className="space-y-5"><Header title="Exercise Details" error={searchParams?.error} message={searchParams?.message} /><Master exercises={exercises} /><Pending items={routineItems} /><Totals totals={totals} /><History logs={logs} /></section>;
}

function Header({ error, message, title }: { error?: string; message?: string; title: string }) { return <><div><h1 className="text-3xl font-semibold">{title}</h1><p className="mt-2 text-slate-300">Manage exercise types, fill details for completed routine items, and track accumulated exercise duration.</p></div>{error ? <p className="rounded-md border border-red-500/40 bg-red-500/10 px-3 py-2 text-sm text-red-200">{error}</p> : null}{message ? <p className="rounded-md border border-emerald-500/40 bg-emerald-500/10 px-3 py-2 text-sm text-emerald-200">{message}</p> : null}</>; }
function Master({ exercises }: { exercises: { id: string; name: string }[] }) { return <section className="rounded-lg border border-slate-800 bg-slate-900 p-5"><h2 className="text-xl font-semibold">Exercise Types</h2><form action={createExerciseType} className="mt-4 grid gap-3 md:grid-cols-[1fr_auto]"><label className="grid gap-1 text-sm">Add Exercise Type<input className="rounded-md border border-slate-700 bg-slate-950 px-3 py-2 text-slate-50" name="name" placeholder="Push Up, Mobility, Basketball Practice" required /></label><button className="self-end rounded-md bg-primary px-4 py-2 font-medium text-white" type="submit">Add</button></form>{exercises.length === 0 ? <p className="mt-3 text-sm text-slate-400">No exercise types yet.</p> : <ul className="mt-4 space-y-2">{exercises.map((exercise) => <li className="flex items-center justify-between gap-3 rounded-md border border-slate-800 bg-slate-950 px-3 py-2" key={exercise.id}><span>{exercise.name}</span><form action={deleteExerciseType}><input name="id" type="hidden" value={exercise.id} /><button className="text-sm text-red-200" type="submit">Delete</button></form></li>)}</ul>}</section>; }
function Pending({ items }: { items: { id: string; displayName: string; durationMinutes: number }[] }) { return <section className="rounded-lg border border-slate-800 bg-slate-900 p-5"><h2 className="text-xl font-semibold">Pending Exercise Details</h2>{items.length === 0 ? <p className="mt-2 text-sm text-slate-400">No completed exercise items are waiting for details.</p> : <div className="mt-4 space-y-3">{items.map((item) => <form action={createExerciseLog} className="grid gap-3 rounded-md border border-slate-800 bg-slate-950 p-4" key={item.id}><input name="dailyRoutineItemId" type="hidden" value={item.id} /><h3 className="font-medium">{item.displayName}</h3><Input defaultValue={String(item.durationMinutes)} label="Duration Minutes" name="durationMinutes" type="number" /><Input label="Sets" name="sets" type="number" /><Input label="Reps" name="reps" type="number" /><Textarea label="Notes" name="notes" /><Button label="Save Exercise Detail" /></form>)}</div>}</section>; }
function Totals({ totals }: { totals: { id: string; name: string; durationMinutes: number; logs: ExerciseLogWithType[] }[] }) { return <section className="rounded-lg border border-slate-800 bg-slate-900 p-5"><h2 className="text-xl font-semibold">Total Duration</h2>{totals.length === 0 ? <p className="mt-2 text-sm text-slate-400">No exercise duration yet.</p> : <div className="mt-4 space-y-3">{totals.map((item) => <details className="rounded-md border border-slate-800 bg-slate-950 p-3" key={item.id}><summary className="cursor-pointer font-medium">{item.name}: {formatMinutes(item.durationMinutes)}</summary><ul className="mt-3 space-y-2 text-sm text-slate-300">{item.logs.length === 0 ? <li>No history yet.</li> : item.logs.map((log) => <li key={log.id}>{log.logDate.toISOString().slice(0, 10)} - {formatMinutes(log.durationMinutes)}{log.notes ? ` - ${log.notes}` : ""}</li>)}</ul></details>)}</div>}</section>; }
function History({ logs }: { logs: ExerciseLogWithType[] }) { return <section className="rounded-lg border border-slate-800 bg-slate-900 p-5"><h2 className="text-xl font-semibold">History</h2>{logs.length === 0 ? <p className="mt-2 text-sm text-slate-400">No logs yet.</p> : <div className="mt-4 space-y-3">{logs.slice(0, 10).map((log) => <form action={updateExerciseLog} className="grid gap-3 rounded-md border border-slate-800 bg-slate-950 p-4" key={log.id}><input name="id" type="hidden" value={log.id} /><h3 className="font-medium">{log.exerciseType.name} - {log.logDate.toISOString().slice(0, 10)}</h3><Input defaultValue={String(log.durationMinutes)} label="Duration Minutes" name="durationMinutes" type="number" /><Input defaultValue={log.sets ? String(log.sets) : ""} label="Sets" name="sets" type="number" /><Input defaultValue={log.reps ? String(log.reps) : ""} label="Reps" name="reps" type="number" /><Textarea defaultValue={log.notes ?? ""} label="Notes" name="notes" /><Button label="Update Exercise Detail" /></form>)}</div>}</section>; }
function Input({ defaultValue, label, name, type = "text" }: { defaultValue?: string; label: string; name: string; type?: string }) { return <label className="grid gap-1 text-sm">{label}<input className="rounded-md border border-slate-700 bg-slate-950 px-3 py-2 text-slate-50" defaultValue={defaultValue} name={name} required={name === "durationMinutes"} type={type} /></label>; }
function Textarea({ defaultValue, label, name }: { defaultValue?: string; label: string; name: string }) { return <label className="grid gap-1 text-sm">{label}<textarea className="rounded-md border border-slate-700 bg-slate-950 px-3 py-2 text-slate-50" defaultValue={defaultValue} name={name} rows={3} /></label>; }
function Button({ label }: { label: string }) { return <button className="rounded-md bg-primary px-4 py-2 font-medium text-white" type="submit">{label}</button>; }

type ExerciseLogWithType = { id: string; logDate: Date; durationMinutes: number; sets: number | null; reps: number | null; notes: string | null; exerciseType: { id: string; name: string } };
